name: push_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  equatable: ^2.0.5
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^14.1.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
