// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXmkvtMHZEhNsEXTk1aqHOp-0K8AOH7E',
    appId: '1:773166065643:web:56728ee2605c435c2d1bae',
    messagingSenderId: '773166065643',
    projectId: 'flutter-tz',
    authDomain: 'flutter-tz.firebaseapp.com',
    databaseURL: 'https://flutter-tz.firebaseio.com',
    storageBucket: 'flutter-tz.appspot.com',
    measurementId: 'G-EGTSNH5ZTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAY1kDcnjRqSjw2IfTZbETMZEMKEXDj2M',
    appId: '1:773166065643:android:18e77fb9b6c6ba0e2d1bae',
    messagingSenderId: '773166065643',
    projectId: 'flutter-tz',
    databaseURL: 'https://flutter-tz.firebaseio.com',
    storageBucket: 'flutter-tz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL4xgCg08yXBSiUYEPR6uW05AA3d0Dhuc',
    appId: '1:773166065643:ios:fb03231ec30c2daa2d1bae',
    messagingSenderId: '773166065643',
    projectId: 'flutter-tz',
    databaseURL: 'https://flutter-tz.firebaseio.com',
    storageBucket: 'flutter-tz.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL4xgCg08yXBSiUYEPR6uW05AA3d0Dhuc',
    appId: '1:773166065643:ios:fb03231ec30c2daa2d1bae',
    messagingSenderId: '773166065643',
    projectId: 'flutter-tz',
    databaseURL: 'https://flutter-tz.firebaseio.com',
    storageBucket: 'flutter-tz.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuXmkvtMHZEhNsEXTk1aqHOp-0K8AOH7E',
    appId: '1:773166065643:web:0d9d2fb900a47b6e2d1bae',
    messagingSenderId: '773166065643',
    projectId: 'flutter-tz',
    authDomain: 'flutter-tz.firebaseapp.com',
    databaseURL: 'https://flutter-tz.firebaseio.com',
    storageBucket: 'flutter-tz.appspot.com',
    measurementId: 'G-6ESNJ70PRL',
  );
}
